### ISSUE TITLE
Totals board: comparison with other users, their activity in the last week, etc. 

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/hexlet-friends#180]
Make a board like the one below. This board should have a function to compare yourself with other users by their activity:

- Per week;
- Month,
- 3 months;
- Year.

Activity:
- Pull request;
- Comments;
- Issues;
- Forks.

<img width="1193" alt="Снимок экрана 2022-07-26 в 3 31 22 PM" src="https://user-images.githubusercontent.com/77053797/181006317-439a311f-9961-47f5-a2bb-ee9cf306d0f8.png">
у

**Comment by sch0nik** [comment]
Я возьму эту задачу.

**Comment by acidmaksim** [comment]
@sch0nik как дела с задачей?

**Comment by sch0nik** [comment]
Я все ещё не понимаю что делать. Как это будет выглядеть. Я с кем-то должен обсудить конечный результат или должен сам сделать? Вроде говорили  что будет созвон. Это сравнение с другими людьми будет на отдельной странице или как.  16:05, 13 октября 2022 г., Maxim Skriov ***@***.***>:
@sch0nik как дела с задачей?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
-- Отправлено из мобильного приложения Яндекс Почты

**Comment by acidmaksim** [comment]
Напиши мне в слаке, а то я не могу тебя по гитхабу идентифицировать) 

Но в целом да, ты можешь сам это сделать. Таблица может выглядеть также, как на скрине выше, просто с другими данными

**Comment by acidmaksim** [comment]
@sch0nik делаешь?

**Comment by sch0nik** [comment]
Да делаю.

**Comment by M1RRoN** [comment]
актуально?

**Comment by sch0nik** [comment]
Да, актуально.

**Comment by LilDrugHill** [comment]
беру

**Comment by sch0nik** [comment]
Извини, не так выразился. Я него делаю.
